FROM jupyter/pyspark-notebook:latest

USER root

# =========================
# Instala dependências S3A
# =========================
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
    -P /usr/local/spark/jars/

RUN wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar \
    -P /usr/local/spark/jars/

# =========================
# Instala Delta Lake
# =========================
RUN wget https://repo1.maven.org/maven2/io/delta/delta-spark_2.12/3.2.0/delta-spark_2.12-3.2.0.jar \
    -P /usr/local/spark/jars/

# =========================
# Permissões corretas
# =========================
RUN chown -R jovyan:users /home/jovyan

USER jovyan